# Generated by Django 5.2.6 on 2025-09-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholarship_tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholarship',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
